// Generated by npm run build.
window.__ModuleLoader__.load({id:'dsh-play-continue',factory:(require)=>{
function empty(input, session) {
  return input?.phase === 'plain' && !input.draft.trim() && input.attachmentIds.length === 0 &&
    session?.openState === 'open' && !session.running && !session.removed && !session.subagent &&
    !session.queue.length && !session.pendingSubmissions.length;
}
function mount(anchor,{sessionId,input,session,language,fetcher=fetch}) {
  const doc=anchor.ownerDocument, win=doc.defaultView;
  const play=doc.createElement('button'); play.type='button'; play.dataset.playContinue=sessionId;
  play.innerHTML='<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M5 3.3c0-.6.7-1 1.2-.7l6.5 4.7c.5.3.5 1.1 0 1.4l-6.5 4.7c-.5.3-1.2-.1-1.2-.7z"/></svg>';
  let native, previousDisplay, stopped=false, busy=false, state=null, generation=0, controller;
  const restore=()=>{play.remove();if(native){native.style.display=previousDisplay;native=undefined;}};
  const sync=()=>{
    const allowed=state?.eligible && empty(input.state.getSnapshot(),session.getSnapshot());
    const card=anchor.closest('[data-composer-card]');
    // Read the host's primary button class from its own stylesheet, not locale text.
    const style=doc.querySelector('style[data-plugin-css$="/InputBar.module.css"]');
    const cls=style?.textContent.match(/\.([\w-]+_primary)\{/u)?.[1];
    const target=cls && card?.querySelector('button.'+cls+':not([data-play-continue])');
    if(!allowed || !target || !target.disabled){restore();return;}
    if(native!==target){restore();native=target;previousDisplay=target.style.display;}
    if(native.style.display!=='none')native.style.display='none';
    play.className=target.className;
    play.disabled=busy;
    const lang=language();const label=lang.startsWith('ru')?'Продолжить':lang.startsWith('zh')?'继续':'Continue';
    play.title=label;play.setAttribute('aria-label',label);
    if(play.parentElement!==target.parentElement)target.after(play);
  };
  const refresh=async()=>{
    const own=++generation;controller?.abort();controller=new AbortController();
    if(session.getSnapshot().running){state=null;sync();return;}
    try {
      const response=await fetcher('/play-continue?'+new URLSearchParams({sessionId}),{signal:controller.signal,credentials:'same-origin'});
      if(!response.ok)throw new Error('Status unavailable');
      const value=await response.json();
      if(!stopped && own===generation){state=value;sync();}
    }catch{if(!stopped && own===generation){state=null;sync();}}
  };
  play.addEventListener('click',async()=>{
    if(busy || !state?.eligible || !empty(input.state.getSnapshot(),session.getSnapshot()))return;
    busy=true;sync();
    try{
      const response=await fetcher('/play-continue',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId,turn:state.turn,language:language().split('-')[0]})});
      const value=await response.json();if(!response.ok)throw new Error(value.error ?? 'Continuation failed.');
      state=null;
    }catch(error){if(!stopped)input.notify('error',error.message);}
    finally{busy=false;if(!stopped){sync();void refresh();}}
  });
  const observer=new win.MutationObserver(sync);
  observer.observe(doc.body,{childList:true,subtree:true});
  const offInput=input.state.subscribe(sync);
  const offSession=session.subscribe(()=>{sync();void refresh();});
  const timer=win.setInterval(refresh,10000);
  void refresh();
  return()=>{stopped=true;generation++;controller?.abort();win.clearInterval(timer);offInput();offSession();observer.disconnect();restore();};
}
const inject=['slots','sessions','conversation','locale'];
function apply(ctx){
  const React=require('react');
  function Play({sessionId}){
    const ref=React.useRef(null);
    React.useEffect(()=>{
      const binding=ctx.sessions.binding(sessionId);
      if(!binding || !ref.current)return;
      return mount(ref.current,{sessionId,input:ctx.conversation.input.for(binding.ctx),session:binding.session,language:()=>ctx.locale.getSnapshot().active});
    },[sessionId]);
    return React.createElement('span',{ref,hidden:true});
  }
  ctx.slots.inject('conversation.input.right',()=>ctx.slots.register({name:'conversation.input.right',id:'play-continue',order:100},Play));
}

return {apply,inject};
}});
