import { readFile, writeFile } from 'node:fs/promises';
const source = await readFile(new URL('./src/client.mjs', import.meta.url), 'utf8');
await writeFile(new URL('./client.js', import.meta.url), `// Generated by npm run build.\nwindow.__ModuleLoader__.load({id: 'dsh-usage-line', factory: (require) => {\n${source.replace(/^export /gm, '')}\nreturn {apply, inject};\n}});\n`);
