// Generated by npm run build.
window.__ModuleLoader__.load({id: 'dsh-usage-line', factory: (require) => {
/** A thin view over token-usage's existing, session-scoped stats endpoint. */
function scopeIds(rows, root) {
  if (!root) return [];
  const ids = new Set([root]);
  let changed = true;
  while (changed) {
    changed = false;
    for (const [id, row] of Object.entries(rows)) {
      if (row.origin === 'subagent' && ids.has(row.parentId) && !ids.has(id)) {
        ids.add(id);
        changed = true;
      }
    }
  }
  return [...ids].sort();
}

function display(summary, lang = 'en') {
  const ru = lang.startsWith('ru'), zh = lang.startsWith('zh');
  const title = ru ? 'Стоимость с субагентами, оценка' : zh ? '含子代理的预估费用' : 'Estimated cost including subagents';
  if (!summary || !Number.isFinite(summary.totalCost) || summary.totalCost < 0 ||
      !Number.isFinite(summary.usdExchangeRate) || summary.usdExchangeRate <= 0 ||
      !Array.isArray(summary.unpricedModels)) throw new Error('Invalid usage summary');
  const usd = summary.totalCost / summary.usdExchangeRate;
  const amount = usd > 0 && usd < .01 ? '<$0.01' : '$' + usd.toFixed(2);
  const unknown = summary.unpricedModels.length > 0;
  return {
    text: `≈ ${amount}${unknown ? ' *' : ''}`,
    title: `${title}: ${amount}. ${ru ? 'Расчёт по таблице цен, не счёт провайдера.' : zh ? '按价格表估算，并非供应商账单。' : 'Price-table estimate, not a provider invoice.'}` +
      (unknown ? ` ${ru ? 'Не учтены модели без цены' : zh ? '未计价模型' : 'Unpriced models excluded'}: ${summary.unpricedModels.join(', ')}` : ''),
  };
}

/** Resolve only the composer's nearest stats row, never another session's row. */
function findStats(anchor) {
  for (let node = anchor.parentElement, depth = 0; node && depth < 6; node = node.parentElement, depth++) {
    if (node === anchor.ownerDocument.body) break;
    const rows = node.querySelectorAll('[data-composer-stats]');
    if (rows.length === 1) return rows[0];
    if (rows.length > 1) return null;
  }
  return null;
}

function mount(anchor, {sessionId, rows, language, fetcher = fetch, interval = 5000}) {
  const doc = anchor.ownerDocument, win = doc.defaultView;
  const pill = doc.createElement('span');
  pill.dataset.usageLine = sessionId;
  pill.tabIndex = 0;
  pill.setAttribute('role', 'status');
  // Native StatsPills has no extension slot. Attach one owned node; never
  // change React-owned children, text, inline styles or the host's layout.
  pill.style.cssText = 'display:inline-flex;align-items:center;gap:6px;white-space:nowrap;font:inherit;color:inherit;padding:1px 8px;border-radius:24px;';
  let view = {text: '≈ $…', title: 'Loading cost'}, stopped = false, controller, timer;
  const attach = () => {
    if (stopped || !anchor.isConnected) return;
    const row = findStats(anchor);
    if (!row) { pill.remove(); return; }
    const native = row.querySelector('button');
    if (native && pill.className !== native.className) pill.className = native.className;
    if (pill.textContent !== view.text) pill.textContent = view.text;
    if (pill.title !== view.title) { pill.title = view.title; pill.setAttribute('aria-label', view.title); }
    if (pill.parentElement !== row) row.append(pill);
  };
  const observer = new win.MutationObserver(attach);
  observer.observe(doc.body, {childList: true, subtree: true});
  const refresh = async () => {
    controller = new AbortController();
    const timeout = win.setTimeout(() => controller.abort(), 10000);
    try {
      const ids = scopeIds(rows(), sessionId);
      const query = new URLSearchParams({fields: 'chip'});
      ids.forEach(id => query.append('sessionId', id));
      const response = await fetcher('/token-usage/stats?' + query, {signal: controller.signal, headers: {accept: 'application/json'}, credentials: 'same-origin'});
      if (!response.ok) throw new Error('HTTP ' + response.status);
      const summary = await response.json();
      if (summary.scope !== 'session' || !Array.isArray(summary.sessionIds) ||
          [...summary.sessionIds].sort().join('\n') !== ids.join('\n')) throw new Error('Wrong session scope');
      if (!stopped) view = display(summary, language());
    } catch {
      if (!stopped) view = {text: '≈ $—', title: language().startsWith('ru') ? 'Стоимость временно недоступна' : 'Cost temporarily unavailable'};
    } finally {
      win.clearTimeout(timeout);
      if (!stopped) { attach(); timer = win.setTimeout(refresh, interval); }
    }
  };
  attach();
  refresh();
  return () => { stopped = true; controller?.abort(); win.clearTimeout(timer); observer.disconnect(); pill.remove(); };
}

const inject = ['slots', 'sessions', 'locale'];
function apply(ctx) {
  const React = require('react');
  function CostLine({sessionId}) {
    const ref = React.useRef(null);
    React.useEffect(() => {
      if (!sessionId || !ref.current) return;
      return mount(ref.current, {
        sessionId,
        rows: () => ctx.sessions.list.getSnapshot().byId,
        language: () => ctx.locale.getSnapshot().active || 'en',
      });
    }, [sessionId]);
    return React.createElement('span', {ref, hidden: true, 'data-usage-line-anchor': sessionId});
  }
  ctx.slots.inject('conversation.composer.dock', () => ctx.slots.register({
    name: 'conversation.composer.dock', id: 'usage-line', order: 100,
  }, CostLine));
}

return {apply, inject};
}});
